apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-bff-service
  labels:
    app: web-bff-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-bff-service
  template:
    metadata:
      labels:
        app: web-bff-service
    spec:
      containers:
        - name: web-bff-service
          image: deepinnext/web-bff-service:8bab60ae9da2b0a0e60ce84eeeb974e5a70221fe
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5