namePrefix: nas-
commonLabels:
  variant: nas
bases:
  - ./../base
patchesStrategicMerge:
  - deployment.yaml
images:
  - name: deepinnext/presence-service
    newTag: a2e5f5521ab13a009bdd70853ce733cbeeb0d3aa
patches:
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: presence-service