namePrefix: nas-
commonLabels:
  variant: nas
bases:
  - ./../base
patchesStrategicMerge:
  - deployment.yaml
images:
  - name: deepinnext/presence-service
    newTag: a83185c6f229cc72d5213eede697ac12db019bf8
patches:
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: presence-service