namePrefix: nas-
commonLabels:
  variant: nas
bases:
  - ./../base
patchesStrategicMerge:
  - deployment.yaml
images:
  - name: deepinnext/presence-service
    newTag: b2b93bcfe8d2ea59008434e6b377b60f976912b9
patches:
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: presence-service