apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  selector:
    app: identity-service
  ports:
    - name: https
      protocol: TCP
      port: 5000
      targetPort: 8081
  type: LoadBalancer
