namePrefix: nas-
commonLabels:
  variant: nas
bases:
  - ./../base
patchesStrategicMerge:
  - deployment.yaml
images:
  - name: deepinnext/message-service
    newTag: fa10ec8a52fd4f98386b5a30ff49c945350315c0
patches:
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: message-service