namePrefix: nas-
commonLabels:
  variant: nas
bases:
  - ./../base
patchesStrategicMerge:
  - deployment.yaml
images:
  - name: deepinnext/message-service
    newTag: 6e1178782159228bf80924391c118488b0bcee0b
patches:
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: message-service