namePrefix: nas-
commonLabels:
  variant: nas
bases:
  - ./../base
patchesStrategicMerge:
  - deployment.yaml
images:
  - name: deepinnext/message-service
    newTag: e388ddc72cc3591a1e1878c5858e908ee9cb1691
patches:
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: message-service