apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: identity-service
          env:
            - name: DEEPIN_ENV
              value: nas
            - name: ConnectionStrings__IdentityDb
              valueFrom:
                secretKeyRef:
                  name: identity-service-secret
                  key: IDENTITY_DB_CONNECTION
            - name: ConnectionStrings__ConfigurationDb
              valueFrom:
                secretKeyRef:
                  name: identity-service-secret
                  key: CONFIGURATION_DB_CONNECTION
            - name: ConnectionStrings__PersistedGrantDb
              valueFrom:
                secretKeyRef:
                  name: identity-service-secret
                  key: PERSISTED_GRANT_DB_CONNECTION
            - name: ConnectionStrings__Redis
              valueFrom:
                secretKeyRef:
                  name: identity-service-secret
                  key: REDIS_CONNECTION
            - name: CERT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: identity-service-secret
                  key: CERT_PASSWORD
            - name: CERT_PATH
              value: /app/certs/deepin.pfx
          volumeMounts:
            - name: pfx-certs
              mountPath: /app/certs
              readOnly: true
      volumes:
        - name: pfx-certs
          hostPath:
            path: /home/leoyang/certs
            type: Directory
