apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: identity-service
          env:
            - name: ASPNETCORE_URLS
              value: "http://*:80;https://+:443"
            - name: ASPNETCORE_HTTPS_PORTS
              value: "443"
            - name: ASPNETCORE_HTTP_PORTS
              value: "80"
            - name: ASPNETCORE_Kestrel__Certificates__Default__Path
              value: "/app/certs/origin-cert-cf.pem"
            - name: ASPNETCORE_Kestrel__Certificates__Default__KeyPath
              value: "/app/certs/private-key-cf.pem"
            - name: DEEPIN_ENV
              value: nas
            - name: ConnectionStrings__IdentityDb
              valueFrom:
                secretKeyRef:
                  name: identity-service-secret
                  key: IDENTITY_DB_CONNECTION
            - name: ConnectionStrings__ConfigurationDb
              valueFrom:
                secretKeyRef:
                  name: identity-service-secret
                  key: CONFIGURATION_DB_CONNECTION
            - name: ConnectionStrings__PersistedGrantDb
              valueFrom:
                secretKeyRef:
                  name: identity-service-secret
                  key: PERSISTED_GRANT_DB_CONNECTION
            - name: ConnectionStrings__Redis
              valueFrom:
                secretKeyRef:
                  name: identity-service-secret
                  key: REDIS_CONNECTION
            - name: CERT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: identity-service-secret
                  key: CERT_PASSWORD
            - name: CERT_PATH
              value: /app/certs/deepin.pfx
            - name: RabbitMQ__Host
              valueFrom:
                secretKeyRef:
                  name: identity-service-secret
                  key: RABBITMQ_HOST
            - name: RabbitMQ__Port
              valueFrom:
                secretKeyRef:
                  name: identity-service-secret
                  key: RABBITMQ_PORT
            - name: RabbitMQ__Username
              valueFrom:
                secretKeyRef:
                  name: identity-service-secret
                  key: RABBITMQ_USERNAME
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: identity-service-secret
                  key: RABBITMQ_PASSWORD
            - name: RabbitMQ__VirtualHost
              valueFrom:
                secretKeyRef:
                  name: identity-service-secret
                  key: RABBITMQ_VHOST
            - name: RabbitMQ__QueueName
              value: identity-service
          volumeMounts:
            - name: certs
              mountPath: /app/certs
              readOnly: true
      volumes:
        - name: certs
          hostPath:
            path: /home/leoyang/certs
            type: Directory
