namePrefix: nas-
commonLabels:
  variant: nas
bases:
  - ./../base
patchesStrategicMerge:
  - deployment.yaml
images:
  - name: deepinnext/identity-service
    newTag: 25e456ea9aba70df98c03e4bc843080c8eb62223
patches:
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: identity-service