namePrefix: nas-
commonLabels:
  variant: nas
bases:
  - ./../base
patchesStrategicMerge:
  - deployment.yaml
images:
  - name: deepinnext/identity-service
    newTag: e2e5c06d199d0d2e8ab7abbe125726e3bbc980fa
patches:
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: identity-service