namePrefix: nas-
commonLabels:
  variant: nas
bases:
  - ./../base
patchesStrategicMerge:
  - deployment.yaml
images:
  - name: deepinnext/identity-service
    newTag: 2b06da6994e8cd1dec58561efc6b051fb6581a40
patches:
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: identity-service