namePrefix: nas-
commonLabels:
  variant: nas
bases:
  - ./../base
patchesStrategicMerge:
  - deployment.yaml
images:
  - name: deepinnext/identity-service
    newTag: 45f44f7dd2d2364dcecea9bf2f07a99dc598f424
patches:
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: identity-service