apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith-service
  labels:
    app: monolith-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: monolith-service
  template:
    metadata:
      labels:
        app: monolith-service
    spec:
      containers:
        - name: monolith-service
          image: deepinchat/monolith-service:28e21d6ec91a7fc63732711c1610ceae970f86b7
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5