apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: identity-server-az-sg
  namespace: argocd
  labels:
    app.kubernetes.io/name: identity-server
    app.kubernetes.io/component: identity-server
    environment: az-sg
spec:
  project: default
  source:
    repoURL: https://github.com/deepinchat/deployments.git
    targetRevision: HEAD
    path: argocd/identity-server/az-sg
  destination:
    server: https://kubernetes.default.svc
    namespace: az-sg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10