apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: az-sg
resources:
  - ../base
patchesStrategicMerge:
  - deployment.yaml
  - ingress.yaml
images:
  - name: deepinchat/identity-server
    newTag: 4f618db776ad6215895b37e2411d0bc39e78aa3f