apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: az-sg
resources:
  - ../base
patchesStrategicMerge:
  - deployment.yaml
  - ingress.yaml
images:
  - name: deepinchat/identity-server
    newTag: 9ddd3106c761ca53c8f057e0108d360c1ef192d8