apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: redis-base

resources:
  - deployment.yaml
  - service.yaml
  - network-policy.yaml
  - pvc.yaml
  # - monitoring.yaml  # Uncomment if you have Prometheus operator

commonLabels:
  app.kubernetes.io/part-of: redis

images:
- name: redis
  newTag: 7.2-alpine