apiVersion: v1
kind: ServiceMonitor
metadata:
  name: redis-monitor
  labels:
    app: redis
    app.kubernetes.io/name: redis
spec:
  selector:
    matchLabels:
      app: redis
  endpoints:
  - port: redis
    interval: 30s
    path: /metrics
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  labels:
    app: redis-exporter
    app.kubernetes.io/name: redis-exporter
spec:
  ports:
  - port: 9121
    targetPort: 9121
    name: metrics
  selector:
    app: redis-exporter
