apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-service
spec:
  replicas: 1
  template:
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: storage-service
          env:
            - name: PathBase
              value: /storage
            - name: DEEPIN_ENV
              value: nas
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: storage-service-secret
                  key: DEFAULT_CONNECTION
            - name: Identity__Url
              value: https://account.deepin.me
            - name: Storage__Provider
              value: Local
            - name: Storage__Root
              value: /app/data
          volumeMounts:
            - name: app-data
              mountPath: /app/data
      volumes:
        - name: app-data
          hostPath:
            path: /home/leoyang/deepin/data
            type: Directory