apiVersion: v1
kind: Service
metadata:
  name: identity-server
spec:
  type: NodePort
  selector:
    app: identity-server
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8081
      nodePort: 30443
