apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: email-service
          env:
            - name: DEEPIN_ENV
              value: nas
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: email-service-secret
                  key: DEFAULT_CONNECTION
            - name: RabbitMQ__Host
              valueFrom:
                secretKeyRef:
                  name: email-service-secret
                  key: RABBITMQ_HOST
            - name: RabbitMQ__Port
              valueFrom:
                secretKeyRef:
                  name: email-service-secret
                  key: RABBITMQ_PORT
            - name: RabbitMQ__Username
              valueFrom:
                secretKeyRef:
                  name: email-service-secret
                  key: RABBITMQ_USERNAME
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: email-service-secret
                  key: RABBITMQ_PASSWORD
            - name: RabbitMQ__VirtualHost
              valueFrom:
                secretKeyRef:
                  name: email-service-secret
                  key: RABBITMQ_VHOST
            - name: RabbitMQ__QueueName
              value: email-service
            - name: Smtp__Host
              valueFrom:
                secretKeyRef:
                  name: email-service-secret
                  key: SMTP_HOST
            - name: Smtp__Port
              valueFrom:
                secretKeyRef:
                  name: email-service-secret
                  key: SMTP_PORT
            - name: Smtp__FromAddress
              valueFrom:
                secretKeyRef:
                  name: email-service-secret
                  key: SMTP_FROM_ADDRESS
            - name: Smtp__FromDisplayName
              valueFrom:
                secretKeyRef:
                  name: email-service-secret
                  key: SMTP_FROM_DISPLAY_NAME
            - name: Smtp__ReplyTo
              valueFrom:
                secretKeyRef:
                  name: email-service-secret
                  key: SMTP_REPLY_TO
            - name: Smtp__Password
              valueFrom:
                secretKeyRef:
                  name: email-service-secret
                  key: SMTP_PASSWORD
