apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: email-service
          env:
            - name: DEEPIN_ENV
              value: nas
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: email-service-secret
                  key: DEFAULT_CONNECTION
            - name: RabbitMQ__Host
              valueFrom:
                secretKeyRef:
                  name: email-service-secret
                  key: RABBITMQ_HOST
            - name: RabbitMQ__Port
              valueFrom:
                secretKeyRef:
                  name: email-service-secret
                  key: RABBITMQ_PORT
            - name: RabbitMQ__Username
              valueFrom:
                secretKeyRef:
                  name: email-service-secret
                  key: RABBITMQ_USERNAME
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: email-service-secret
                  key: RABBITMQ_PASSWORD
            - name: RabbitMQ__VirtualHost
              valueFrom:
                secretKeyRef:
                  name: email-service-secret
                  key: RABBITMQ_VHOST
            - name: RabbitMQ__QueueName
              value: email-service
