namePrefix: nas-
commonLabels:
  variant: nas
bases:
  - ./../base
images:
  - name: deepinnext/email-service
    newTag: 4fd1839acd50792695230bfbab92005adc72e7fd
patches:
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: email-service