apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin-ingress
spec:
  rules:
  - host: pgadmin-az-sg.deepin.app
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: pgadmin
            port:
              number: 80