apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin-ingress
spec:
  tls:
    - hosts:
        - pgadmin-az-sg.deepin.app
      secretName: deepin-app-tls
  rules:
  - host: pgadmin-az-sg.deepin.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pgadmin
            port:
              number: 80