apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: email-service
spec:
  project: default
  source:
    path: k8s/email-service
    repoURL: https://github.com/deepinnext/email-service.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      