namePrefix: nas-
commonLabels:
  variant: nas
bases:
  - ./../base
patchesStrategicMerge:
  - deployment.yaml
images:
  - name: deepinnext/chat-service
    newTag: 224e4df8c3f00bd02a577f05beddf4fbba33f787
patches:
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: chat-service