namePrefix: nas-
commonLabels:
  variant: nas
bases:
  - ./../base
patchesStrategicMerge:
  - deployment.yaml
images:
  - name: deepinnext/web-bff-service
    newTag: 26c4ec1d8379c3dd124fdcb2d98abc712f808d9d
patches:
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: web-bff-service