namePrefix: nas-
commonLabels:
  variant: nas
bases:
  - ./../base
patchesStrategicMerge:
  - deployment.yaml
images:
  - name: deepinnext/web-bff-service
    newTag: 77a9517cdbcd7cd91b82ed829a378b7baf337c2d
patches:
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: web-bff-service