namePrefix: nas-
commonLabels:
  variant: nas
bases:
  - ./../base
patchesStrategicMerge:
  - deployment.yaml
images:
  - name: deepinnext/web-bff-service
    newTag: f795d29b9646eb69fc20940073080efb4b6477fd
patches:
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: web-bff-service