namePrefix: nas-
commonLabels:
  variant: nas
bases:
  - ./../base
patchesStrategicMerge:
  - deployment.yaml
images:
  - name: deepinnext/web-bff-service
    newTag: 1695e9b53ed2c43a7a1ac13b7b5a93a3bbc71668
patches:
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: web-bff-service