namePrefix: production-
commonLabels:
  variant: production
bases:
  - ./../base
patchesStrategicMerge:
  - deployment.yaml
images:
  - name: deepinnext/email-service
    newTag: d690909cf5128c21da5992fe3469b3c1c28519ce
    