namePrefix: nas-
commonLabels:
  variant: nas
bases:
  - ./../base
patchesStrategicMerge:
  - deployment.yaml
images:
  - name: deepinnext/identity-server
    newTag: 8e3b13a52ae2d0b61ab492a06447acc6d7cba0e4
patches:
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: identity-server