namePrefix: nas-
commonLabels:
  variant: nas
bases:
  - ./../base
patchesStrategicMerge:
  - deployment.yaml
images:
  - name: deepinnext/identity-server
    newTag: d4d5502f2a6d2e80532530d055d49c0804d80255