namePrefix: nas-
commonLabels:
  variant: nas
bases:
  - ./../base
patchesStrategicMerge:
  - deployment.yaml
images:
  - name: deepinnext/identity-server
    newTag: 97f908bb49bfc576d1b1a80fe6a3f15067ff37fb
patches:
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: identity-server