apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith-service
spec:
  replicas: 2
  template:
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: monolith-service
          volumeMounts:
            - name: certs
              mountPath: /app/certs
              readOnly: true
      volumes:
        - name: certs
          hostPath:
            path: /home/leoyang/certs/deepin.app
            type: Directory
        - name: app-data
          hostPath:
            path: /home/leoyang/deepin/data
            type: Directory
