apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: az-sg
resources:
  - ../base
patchesStrategicMerge:
  - deployment.yaml
images:
  - name: deepinchat/monolith-service
    newTag: 8f673550d87d9df8ca3c48ea7eab55177935bee3