apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: az-sg
resources:
  - ../base
patchesStrategicMerge:
  - deployment.yaml
images:
  - name: deepinchat/monolith-service
    newTag: 4bdd0545692ab0448106b9e969e8ac530fd719d4