apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: az-sg

resources:
  - ../base

patchesStrategicMerge:
  - deployment.yaml
  - ingress.yaml

labels:
  - pairs:
      environment: az-sg
