apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith-service
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: monolith-service
          env:
            - name: DEEPIN_ENV
              value: staging
            - name: Identity__Url
              value: https://account.deepin.me
            - name: ConnectionStrings__Chat
              valueFrom:
                secretKeyRef:
                  name: monolith-service-secret
                  key: CHAT_DB_CONNECTION
            - name: ConnectionStrings__Contact
              valueFrom:
                secretKeyRef:
                  name: monolith-service-secret
                  key: CONTACT_DB_CONNECTION
            - name: ConnectionStrings__Message
              valueFrom:
                secretKeyRef:
                  name: monolith-service-secret
                  key: MESSAGE_DB_CONNECTION
            - name: ConnectionStrings__Storage
              valueFrom:
                secretKeyRef:
                  name: monolith-service-secret
                  key: STORAGE_DB_CONNECTION
            - name: ConnectionStrings__Notification
              valueFrom:
                secretKeyRef:
                  name: monolith-service-secret
                  key: NOTIFICATION_DB_CONNECTION
            - name: ConnectionStrings__Identity
              valueFrom:
                secretKeyRef:
                  name: monolith-service-secret
                  key: IDENTITY_DB_CONNECTION
            - name: Redis__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: monolith-service-secret
                  key: REDIS_CONNECTION
            - name: RabbitMQ__Host
              valueFrom:
                secretKeyRef:
                  name: monolith-service-secret
                  key: RABBITMQ_HOST
            - name: RabbitMQ__Port
              valueFrom:
                secretKeyRef:
                  name: monolith-service-secret
                  key: RABBITMQ_PORT
            - name: RabbitMQ__Username
              valueFrom:
                secretKeyRef:
                  name: monolith-service-secret
                  key: RABBITMQ_USERNAME
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: monolith-service-secret
                  key: RABBITMQ_PASSWORD
            - name: RabbitMQ__VirtualHost
              valueFrom:
                secretKeyRef:
                  name: monolith-service-secret
                  key: RABBITMQ_VHOST
            - name: RabbitMQ__QueueName
              value: monolith-service
            - name: Smtp__Host
              valueFrom:
                secretKeyRef:
                  name: monolith-service-secret
                  key: SMTP_HOST
            - name: Smtp__Port
              valueFrom:
                secretKeyRef:
                  name: monolith-service-secret
                  key: SMTP_PORT
            - name: Smtp__FromAddress
              valueFrom:
                secretKeyRef:
                  name: monolith-service-secret
                  key: SMTP_FROM_ADDRESS
            - name: Smtp__FromDisplayName
              valueFrom:
                secretKeyRef:
                  name: monolith-service-secret
                  key: SMTP_FROM_DISPLAY_NAME
            - name: Smtp__ReplyTo
              valueFrom:
                secretKeyRef:
                  name: monolith-service-secret
                  key: SMTP_REPLY_TO
            - name: Smtp__Password
              valueFrom:
                secretKeyRef:
                  name: monolith-service-secret
                  key: SMTP_PASSWORD
            - name: Storage__Provider
              value: local
            - name: Storage__FileSystem__RootPath
              value: /app/data
          volumeMounts:
            - name: app-data
              mountPath: /app/data
      volumes:
        - name: app-data
          hostPath:
            path: /home/leoyang/deepin/data
            type: Directory
