apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: rabbitmq-base

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: rabbitmq

images:
- name: rabbitmq
  newTag: 4-management-alpine